#!/usr/bin/env ruby

pid = Process.pid
stdout = STDOUT

Signal.trap("QUIT")do
  stdout.puts "[#{pid}] nginx_supervisor: trapped quit signal ..."
end

cmd = "nginx -c /usr/app/src/nginx/nginx.conf"

stdout.puts "[#{pid}] nginx_supervisor: starting nginx ..."

Kernel.system(cmd)
