#!/usr/bin/env ruby

require "async"
require "async/http/endpoint"
require "async/websocket/client"

URL = ARGV.pop || "http://localhost:7070"

Async do |task|
  endpoint = Async::HTTP::Endpoint.parse(URL)

  Async::WebSocket::Client.connect(endpoint) do |connection|
    connection.write(["message 1"])

    while message = connection.read
      p message
    end
  end
end
