#!/usr/bin/env ruby

require "optparse"

require "./boot.rb"

options = {
  city: nil,
  name: nil,
  street: nil,
}

parser = OptionParser.new do |opts|
  opts.on('--name name', "place name") do |s|
    options[:name] = s
  end

  opts.on('--city city', "city name") do |s|
    options[:city] = s
  end

  opts.on('--street street', "street name and number") do |s|
    options[:street] = s
  end

  opts.on('--lat latitude', "place latitude") do |s|
    options[:lat] = s.to_f
  end
  
  opts.on('--lon longitude', "place longitude") do |s|
    options[:lon] = s.to_f
  end


  opts.on('-h', '--help', 'help') do
    puts opts.to_s
    exit
  end
end

parser.parse!

subject = "Mapbox Import"

city = options.fetch(:city)
name = options.fetch(:name)
street = options.fetch(:street)

if not city or not name or not street
  Console.logger.error(subject, "missing required param")
  exit(1)
end

create_result = ::Service::Places::CreateFromAddress.new(name: name, street: street, city: city, postal: "").call

if create_result.code != 0
  exit(create_result.code)
end

place = create_result.places[0]

Console.logger.info(subject, "place created #{place.id}")
